# Generated by Django 3.2.25 on 2025-10-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251023_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='joined',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
