# Generated by Django 5.2.3 on 2025-07-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dareexchange_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='phone_number',
            field=models.CharField(default=8619270196, max_length=10),
            preserve_default=False,
        ),
    ]
