# Generated by Django 5.2.3 on 2025-07-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dareexchange_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dareexchange',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
