# Generated by Django 5.2.3 on 2025-07-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_dareexchange_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dareexchange',
            name='dare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dareexchange',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
