# Generated by Django 5.2.3 on 2025-07-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_dareexchange_dare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dareexchange',
            name='dare',
            field=models.TextField(default=54544554),
            preserve_default=False,
        ),
    ]
