# Generated by Django 5.2.3 on 2025-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_dareexchange_dare'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dareexchange',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
