# Generated by Django 5.2.4 on 2025-07-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_dareexchange_is_edited_alter_dareexchange_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dareexchange',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
